name: Fetch MLB Savant Data

on:
  schedule:
    - cron: "0 14 * * *"   # 8:00 AM America/Edmonton
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 25

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install "pybaseball==2.2.7" pandas requests

      - name: Fetch latest Statcast (last 7 days)
        env:
          DAYS: "7"
        run: python scripts/fetch_mlb_savant.py

      - name: Commit & push CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/mlb_savant/*.csv || true
          git commit -m "Update MLB Savant data $(date -u +%FT%TZ)" || echo "No changes"
          git push origin HEAD:${{ github.ref_name }} || true

      # 👇 Auto-trigger full pipeline
      - name: Trigger full pipeline
        if: success()
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: mlb_savant_pipeline.yml
          ref: main
