name: Fetch MLB Savant Data

on:
  schedule:
    - cron: "0 14 * * *"   # 8:00 AM MDT (14:00 UTC)
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repo
      # v4 is correct for actions/checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install "pybaseball==2.2.7" pandas

      - name: Fetch latest Statcast (last 7 days)
        env:
          DAYS: "7"
        run: |
          python scripts/fetch_mlb_savant.py

      - name: Commit & push CSVs
        run: |
          git config user.name "gh-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/mlb_savant/*.csv || true
          git commit -m "Update MLB Savant data $(date -u +%FT%TZ)" || echo "No changes"
          git push || true
