name: Fetch MLB Savant Data

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <<— allow pushing
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true   # uses GITHUB_TOKEN

      # ... your install + fetch steps ...

      - name: Commit & push CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/mlb_savant/*.csv || true
          git commit -m "Update MLB Savant data $(date -u +%FT%TZ)" || echo "No changes"
          # Push back to the same branch the workflow runs on:
          git push origin HEAD:${{ github.ref_name }}
