name: Fetch MLB Savant Data

on:
  schedule:
    - cron: "15 16 * * *"  # 10:15 AM America/Edmonton
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install "pybaseball==2.2.7" pandas requests

      - name: Run Savant fetcher
        env:
          DAYS: 7
        run: python scripts/fetch_mlb_savant.py

      - name: Commit new data if changed
        id: commit_data
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/mlb_savant/*.csv 2>/dev/null || true
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes to commit."
          else
            git commit -m "Update MLB Savant data $(date -u +%FT%TZ)"
            git push origin HEAD:main
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlb-savant-${{ github.run_id }}
          path: data/mlb_savant/**/*.csv
