- name: Trigger full pipeline
  if: success()
  uses: peter-evans/workflow-dispatch@v2
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    repository: ${{ github.repository }}
    workflow: mlb_savant_pipeline.yml
    ref: main
